// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPgHSmuH_63q8Kxt17DDTIhfUAy0qLPqE',
    appId: '1:647342014739:web:1ee5e0abe1d66faf5e9ae6',
    messagingSenderId: '647342014739',
    projectId: 'quizlet-clone-fp',
    authDomain: 'quizlet-clone-fp.firebaseapp.com',
    storageBucket: 'quizlet-clone-fp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACViW_gUARg0aptWt_0KNufNRVFg8GB2A',
    appId: '1:647342014739:android:1f7c0c4827af1ca95e9ae6',
    messagingSenderId: '647342014739',
    projectId: 'quizlet-clone-fp',
    storageBucket: 'quizlet-clone-fp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRbrNDdAes17QAoj1eWneCgRJBjwJrDGU',
    appId: '1:647342014739:ios:0c6b0d6f92dc92445e9ae6',
    messagingSenderId: '647342014739',
    projectId: 'quizlet-clone-fp',
    storageBucket: 'quizlet-clone-fp.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRbrNDdAes17QAoj1eWneCgRJBjwJrDGU',
    appId: '1:647342014739:ios:0c6b0d6f92dc92445e9ae6',
    messagingSenderId: '647342014739',
    projectId: 'quizlet-clone-fp',
    storageBucket: 'quizlet-clone-fp.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPgHSmuH_63q8Kxt17DDTIhfUAy0qLPqE',
    appId: '1:647342014739:web:f94156ff67e45ee35e9ae6',
    messagingSenderId: '647342014739',
    projectId: 'quizlet-clone-fp',
    authDomain: 'quizlet-clone-fp.firebaseapp.com',
    storageBucket: 'quizlet-clone-fp.appspot.com',
  );

}